// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5ZRkTOWEE-9O9HxScFxn0Q9HsNdixnY',
    appId: '1:777382167262:android:76282da1e4a1046129f84f',
    messagingSenderId: '777382167262',
    projectId: 'bot-creator-f884b',
    storageBucket: 'bot-creator-f884b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK1o4PAeInCotKhGH_qLI-6eShgjJK6Bc',
    appId: '1:777382167262:ios:083d0f09a8b8ea9329f84f',
    messagingSenderId: '777382167262',
    projectId: 'bot-creator-f884b',
    storageBucket: 'bot-creator-f884b.firebasestorage.app',
    androidClientId: '777382167262-akm5kepn8uhq60vfautku47472vphvc9.apps.googleusercontent.com',
    iosClientId: '777382167262-2clnpnd4ijkjp71gvmpp5u0rik446kn8.apps.googleusercontent.com',
    iosBundleId: 'fr.botcreator.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5yd4n-tBx3j1W4eGPNBAO-aeGguTNSkg',
    appId: '1:777382167262:web:22e57d04163e990029f84f',
    messagingSenderId: '777382167262',
    projectId: 'bot-creator-f884b',
    authDomain: 'bot-creator-f884b.firebaseapp.com',
    storageBucket: 'bot-creator-f884b.firebasestorage.app',
    measurementId: 'G-M83RVGEH2C',
  );

}